[versions]
agp = "8.6.0"
kotlin = "1.9.0"
coreKtx = "1.13.1"
appcompat = "1.7.0"
material = "1.12.0"
constraintlayout = "2.1.4"
recyclerview = "1.3.2"
activity = "1.9.2"
fragment = "1.8.3"
navigation = "2.8.3"
legacySupportV4 = "1.0.0"
firebaseFirestoreKtx = "25.1.1"
guava = "32.1.3-android"
gson = "2.11.0"
flexbox = "3.0.0"
commonsMath = "3.6.1"
mpAndroidChart = "v3.1.0"
kotlinxCoroutines = "1.8.1"
junit = "4.13.2"
extJunit = "1.2.1"
espressoCore = "3.6.1"
googleServices = "4.4.2"

[plugins]
androidApplication = { id = "com.android.application", version.ref = "agp" }
kotlinAndroid = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
googleServices = { id = "com.google.gms.google-services", version.ref = "googleServices" }

[libraries]
core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtx" }
appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompat" }
material = { module = "com.google.android.material:material", version.ref = "material" }
constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayout" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerview" }
activity = { module = "androidx.activity:activity-ktx", version.ref = "activity" }
fragment = { module = "androidx.fragment:fragment-ktx", version.ref = "fragment" }
navigation-fragment = { module = "androidx.navigation:navigation-fragment", version.ref = "navigation" }
navigation-ui = { module = "androidx.navigation:navigation-ui", version.ref = "navigation" }
legacy-support-v4 = { module = "androidx.legacy:legacy-support-v4", version.ref = "legacySupportV4" }
firebase-firestore-ktx = { module = "com.google.firebase:firebase-firestore-ktx", version.ref = "firebaseFirestoreKtx" }
guava = { module = "com.google.guava:guava", version.ref = "guava" }
gson = { module = "com.google.code.gson:gson", version.ref = "gson" }
flexbox = { module = "com.google.android:flexbox", version.ref = "flexbox" }
commons-math3 = { module = "org.apache.commons:commons-math3", version.ref = "commonsMath" }
mpandroidchart = { module = "com.github.PhilJay:MPAndroidChart", version.ref = "mpAndroidChart" }
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinxCoroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinxCoroutines" }
junit = { module = "junit:junit", version.ref = "junit" }
ext-junit = { module = "androidx.test.ext:junit", version.ref = "extJunit" }
espresso-core = { module = "androidx.test.espresso:espresso-core", version.ref = "espressoCore" }



